sudo: false

language: python

python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

install:
  - pip install six
  - pip install flake8
  - pip install -e .
  - pip install tox-travis

script:
  - tox
  - flake8 tests/issues
