sudo: false

language: python

python:
  - "2.7"
  - "3.5"
  - "3.4"

install:
  - pip install six
  - pip install flake8
  - pip install -e .
  - pip install tox-travis

script:
  - tox
  - flake8 tests/real_test.py
