sudo: false

services:
    - docker

env:
    - PYTHON_VERSION=3.6 FLAKE8_VERSION=flake8>=3.0.0
    - PYTHON_VERSION=3.7 FLAKE8_VERSION=flake8>=3.0.0
    - PYTHON_VERSION=3.8-rc FLAKE8_VERSION=flake8>=3.0.0

    before_script:
    - sed -i '' -e "s/{PYTHON_VERSION}/$PYTHON_VERSION/g" Dockerfile
    - sed -i '' -e "s/{FLAKE8_VERSION}/$FLAKE8_VERSION/g" Dockerfile

script:
    - docker build .
